### ISSUE TITLE
Missing “final_result” in argments

### ISSUE THREAD

**Issue by passermyh** [sung-won-kim/TEG#1]
Thanks for your work!
Only need to add it in "argument.py"
![image](https://github.com/sung-won-kim/TEG/assets/71198047/12ccd0dc-e652-43e5-9407-1cc0ae2128b4)
![image](https://github.com/sung-won-kim/TEG/assets/71198047/e30a04fc-25b3-4e0d-9241-ba5f05956782)

By the way, as I'm a beginner, I'd like to know how to generate such pictures. 
Thank you very much!
![image](https://github.com/sung-won-kim/TEG/assets/71198047/e9416704-f83e-47d4-846a-cd9540880d10)

**Comment by passermyh** [comment]
Maybe I misunderstand something. It's blank after I running the example. So what should it be?
![image](https://github.com/sung-won-kim/TEG/assets/71198047/6adffec1-f953-4392-a41f-4619ad22462c)

**Comment by sung-won-kim** [comment]
Hi, thank you for pointing out this.

Actually, you don't need that argument since I personally used it for reporting results.
I have now fixed the code.

Regarding the figure, I used `seaborn.heatmap`.

Thank you.
